import { Inter } from "next/font/google";
import { Footer } from "./_components/footer";
import { Navbar } from "./_components/navbar";
import { Metadata } from "next";
import { siteConfig } from "@/config/site";
const inter =Inter({subsets:['latin']})

export const metadata:Metadata={
    title:{
        default: siteConfig.name
    }
    description:"Generated by create next app"
}
export default function RootLayout ({children}:{
    children:React.ReactNode;
}){
    return (
        <div className="h-full bg-slate-100">
          <Navbar/>
            <main className="pt-40 pd-20 bg-slate-100">
                {children}
            </main>
           <Footer/>
        </div>
    )
}
